ALTER TABLE bar_products ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE billiard ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE employees ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE employee_loans ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE expenses ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE guesthouse ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE gym ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE kitchen_products ADD COLUMN branch_id VARCHAR(50) DEFAULT NULL;
